import pygame
import numpy as np

class Button(pygame.sprite.Sprite): 
    def __init__(self,screen,XShift,YShift,SCREEN_WIDTH,SCREEN_HEIGHT):
        """creates a button object which can be turned into a variety of kinds of buttons (some of these arent actual buttons just kinda didnt wanna make 1 billion classes)

            DecoButton: Cool looking button with two cards next to the button, card can change depending on if user is hovering or not,can call a function on click
            TextButton: Draws a rectangle of buttonColor color and draws text on top of it
            CardButton: A solitary card that grows when hovered over and rotates, can call a function on click

        Args:
            screen (surface): pass in screen object
            XShift (int): integer to shift X position of button
            YShift (int): integer to shift Y position of button
            SCREEN_WIDTH (int): Pass global screen width var
            SCREEN_HEIGHT (int): Pass global screen height var
        """        
        self.screen = screen
        self.buttonXShift = XShift
        self.buttonYShift = YShift
        self.font = pygame.font.Font("assets/fonts/KGPerfectPenmanship.ttf",60)
        self.SCREEN_WIDTH = SCREEN_WIDTH
        self.SCREEN_HEIGHT = SCREEN_HEIGHT

    def DecoButton(self, buttonText, buttonSize, buttonColor, cardFilePath, hoverCardFilePath, events, mouseUpAction = lambda: None):
        """Generates a decorative button with two swaying cards on either side which runs mouseUpAction on mouseup (click)

        Args:
            buttonText (str): text that appears on button
            buttonSize (tuple of ints): (button height,button width)
            buttonColor (tuple): (red,green,blue) 0-255
            cardFilePath (str): File path of card that appears when mouse isnt hovering button
            hoverCardFilePath (str): File path of the card that appears when mouse is hovering button
            events (list): list of events generated by pygame
            mouseUpAction (function): Function you want to run after clicking button
        """
        
        self.buttonSurface = pygame.Surface(buttonSize)
        self.buttonRect = self.buttonSurface.get_rect(center=(self.SCREEN_WIDTH/2 + self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift))        
        if self.buttonRect.collidepoint(pygame.mouse.get_pos()): #check to see if mouse is hovering the button
            self.buttonSurface = pygame.transform.smoothscale(self.buttonSurface, ((buttonSize[0]*1.1,buttonSize[1]*1.1))) #make the button bigger if youre hovering it to indicate it is selected
            self.buttonRect = self.buttonSurface.get_rect(center=(self.SCREEN_WIDTH/2 +self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift)) #move button into position
            self.buttonSurface.fill(buttonColor) #color the button
            self.buttonTextSurface = self.font.render(buttonText, True, (10, 10, 10)) #create surface for the text on the button
            self.buttonTextRect = self.buttonTextSurface.get_rect(center=(self.SCREEN_WIDTH/2 + self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift)) # move the text into position

            self.screen.blit(self.buttonSurface, self.buttonRect) # paste button onto screen
            self.screen.blit(self.buttonTextSurface, self.buttonTextRect) # paste text onto screen
            # start of Code for decorative rotating cards
            self.buttonDecoSurface = pygame.image.load(hoverCardFilePath).convert_alpha() #documentation states that using .convert() after loading a surface dramatically increases speed
            self.buttonDecoSurface = pygame.transform.rotozoom(self.buttonDecoSurface, 4*np.cos(pygame.time.get_ticks()/300),0.15)
            self.buttonDecoRect0 = self.buttonDecoSurface.get_rect(center=(self.buttonRect.left,self.SCREEN_HEIGHT/2 +self.buttonYShift))
            self.buttonDecoRect1 = self.buttonDecoSurface.get_rect(center=(self.buttonRect.right,self.SCREEN_HEIGHT/2 +self.buttonYShift))

            self.screen.blit(self.buttonDecoSurface,self.buttonDecoRect0)
            self.screen.blit(self.buttonDecoSurface,self.buttonDecoRect1)
            # end of Code for decorative rotating cards
            # start of code for click detection and "screen change"
            for event in events:  # Process all events in the queue
                if event.type == pygame.MOUSEBUTTONUP:  # Check for mouse button release
                    mouseUpAction()  # Execute the action
            # end of code for click detection and "screen change"
        else:
            self.buttonSurface = pygame.transform.smoothscale(self.buttonSurface, ((buttonSize[0],buttonSize[1]))) # make the button the original size when not hovering
            self.buttonRect = self.buttonSurface.get_rect(center=(self.SCREEN_WIDTH/2 + self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift)) #move button into position                self.buttonSurface.fill((133, 198, 255)) # color the button
            self.buttonTextSurface = self.font.render(buttonText, True, (10, 10, 10)) # create surface for the text on the button
            self.buttonTextRect = self.buttonTextSurface.get_rect(center=(self.SCREEN_WIDTH/2 + self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift)) # move the text into position
            self.buttonSurface.fill(buttonColor) #color the button

            self.screen.blit(self.buttonSurface, self.buttonRect) # paste button onto screen
            self.screen.blit(self.buttonTextSurface, self.buttonTextRect) # paste text onto screen
            # start of Code for decorative static cards
            self.buttonDecoSurface = pygame.image.load(cardFilePath).convert_alpha() #documentation states that using .convert() after loading a surface dramatically increases speed
            self.buttonDecoSurface = pygame.transform.rotozoom(self.buttonDecoSurface, 0,0.15)
            self.buttonDecoRect0 = self.buttonDecoSurface.get_rect(center=(self.buttonRect.left,self.SCREEN_HEIGHT/2 +self.buttonYShift))
            self.buttonDecoRect1 = self.buttonDecoSurface.get_rect(center=(self.buttonRect.right,self.SCREEN_HEIGHT/2 +self.buttonYShift))

            self.screen.blit(self.buttonDecoSurface,self.buttonDecoRect0)
            self.screen.blit(self.buttonDecoSurface,self.buttonDecoRect1)

    def TextButton(self, buttonText, buttonSize, buttonColor, fontsize):
        """generates a box of arbitrary color with arbitrary text at an arbitrary size, mainly for instructions

        Args:
            buttonText (str): text to be displayed on button
            buttonSize (tuple): size of button in pixels (height, width)
            buttonColor (tuple): color as RGB values (R,G,B)
            fontsize (int): int of fontsize
        """        
        self.buttonSurface = pygame.Surface(buttonSize)
        self.buttonRect = self.buttonSurface.get_rect(center=(self.SCREEN_WIDTH/2 + self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift)) 
        self.font = pygame.font.Font("assets/fonts/KGPerfectPenmanship.ttf", fontsize)
        
        self.buttonRect = self.buttonSurface.get_rect(center=(self.SCREEN_WIDTH/2 + self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift)) #move button into position 
        self.buttonSurface.fill(buttonColor) #color the button

        self.buttonTextSurface = self.font.render(buttonText, True, (10, 10, 10)) # create surface for the text on the button
        self.buttonTextRect = self.buttonTextSurface.get_rect(center=(self.SCREEN_WIDTH/2 + self.buttonXShift,(self.SCREEN_HEIGHT/2)+self.buttonYShift)) # move the text into position

        self.screen.blit(self.buttonSurface, self.buttonRect) # paste button onto screen
        self.screen.blit(self.buttonTextSurface, self.buttonTextRect) # paste text onto screen

    def CardButton(self, cardFilePath, scaleCoeff=0.2, angle = 0, flipped = False, mouseUpAction = lambda: None): 
        """Generates a card that can be either flipped or showing its an arbitrary card, can call a function on mouse click

        Args:
            cardFilePath (str): string describing the file path of card to be drawn (use dict!)
            scaleCoeff (float, optional): size of the card, use small numbers. Defaults to 0.2.
            angle (int, optional): angle of the card. Defaults to 0.
            flipped (bool, optional): if the card should be flipped or not. Defaults to False.
            mouseUpAction (function, optional): function to be called on click. Defaults to lambda:None.
        """        
        if flipped == False:
            self.cardSurface = pygame.image.load(cardFilePath).convert_alpha()
        else:
            self.cardSurface = pygame.image.load("assets/cards/3x/cardback@3x.png").convert_alpha()

        self.cardSurface = pygame.transform.rotozoom(self.cardSurface, angle, scaleCoeff)
        self.cardRect = self.cardSurface.get_rect(center=(self.SCREEN_WIDTH/2 +self.buttonXShift,self.SCREEN_HEIGHT/2 +self.buttonYShift))

        if self.cardRect.collidepoint(pygame.mouse.get_pos()): #check to see if mouse is hovering the button
            self.cardSurface = pygame.transform.rotozoom(self.cardSurface, 4*np.cos(pygame.time.get_ticks()/300), 1.15)
            self.cardRect = self.cardSurface.get_rect(center=(self.SCREEN_WIDTH/2 +self.buttonXShift,self.SCREEN_HEIGHT/2 +self.buttonYShift))
            self.screen.blit(self.cardSurface,self.cardRect)
            for event in pygame.event.get():  # Process all events in the queue
                if event.type == pygame.MOUSEBUTTONUP:  # Check for mouse button release
                    mouseUpAction()  # Execute the action
            # end of code for click detection and "screen change"
            
        else:
            self.cardSurface = pygame.transform.rotozoom(self.cardSurface, 0, 1)
            self.cardRect = self.cardSurface.get_rect(center=(self.SCREEN_WIDTH/2 +self.buttonXShift,self.SCREEN_HEIGHT/2 +self.buttonYShift))
            self.screen.blit(self.cardSurface,self.cardRect)
